### ISSUE TITLE
stone of Greater inertia bug 

### ISSUE THREAD

**Issue by SpGilbert** [XzeroAir/Trinkets-1.12.2#11] opened 2019-02-26 05:55 UTC
your hand starts flashing when you are holding no item when wearing the inviability cloak from aether legacy and the stone of greater inertia from this mod.

**Comment by XzeroAir** [comment] 2019-03-01 20:41
#Starts Flashing? Hmm, if you are using the current latest version of Trinkets and Baubles, The Stone of Greater Inertia doesn't have any rendering code that could cause that on my  #end, but I will look into it and see what I can find

**Comment by XzeroAir** [comment] 2019-04-07 03:11
I Haven't been able to reproduce this issue, It was most likely caused by a Combination of mods or something, closing this for now

**Closed by XzeroAir** 2019-04-07 03:11 UTC
Labels: Can't reproduce
