### ISSUE TITLE
Hi I found something wrong, but I don't understand how it happened and I was hoping you could fix it

### ISSUE THREAD

**Issue by mcmso** [XzeroAir/Trinkets-1.12.2#63] opened 2022-04-23 02:10 UTC
**Describe the bug**
Installing SweetMagic and Trinkets+and+Baubles at the same time can cause this problem
It causes the witch in Sweet Magic to not spawn properly
**Screenshots**

**Version (please complete the following information):**
 - Version [Trinkets+and+Baubles-0.31.4]
Version SweetMagic-1.3.1-beta1.1.jar
**Additional context**

**Comment by NyanMC** [comment] 2022-04-23 02:14
i think this is a duplicate of #62

**Comment by XzeroAir** [comment] 2022-04-23 02:14
Yes, It's the same issue

**Comment by XzeroAir** [comment] 2022-04-23 02:16
If @mcmso wants to Test what I suggested in the other issue, that could help me out a bit.
Try spawning a Frost Skull using a spawn egg and letting me know if it causes a crash or not, If it doesn't crash, then it's most likely on Sweet Magic's End

**Comment by mcmso** [comment] 2022-04-23 02:24
> If @mcmso wants to Test what I suggested in the other issue, that could help me out a bit. Try spawning a Frost Skull using a spawn egg and letting me know if it causes a crash or not, If it doesn't crash, then it's most likely on Sweet Magic's End

![image](https://user-images.githubusercontent.com/46519955/164865942-0b91b07e-4a31-4c95-96b0-69410594795c.png)
What doesn't seem to happen when Frost Skull is generated

**Comment by XzeroAir** [comment] 2022-04-23 02:35
If it doesn't crash when spawning Frost Skulls, then Yeah, Looks like it's on Sweet Magics side, they seem to be missing overrides in the methods they're using when trying to give entities their basic attributes.
when I looked at Sweet Magics source, some entities were fine, but most were missing the overrides.

I'm using a Vanilla Minecraft Method to Check if the entity is a Boss or not, It crashes during that check because Sweet Magic overrides that check in their entity and replaces it with a check for how much health their entity has, but the entity is lacking the Max Health Attribute either for the previously mentioned missing overrides, or something else, resulting in a null pointer.

the reason they're not spawning is probably because in your configs you have it set so forge removes erroring entities, so they just don't spawn, instead of crashing the game, Spawn Eggs bypass that, resulting in a crash instead.

**Closed as completed** 2022-07-02 17:16 UTC
Labels: duplicate, Mod Conflict, Can't Fix
