### ISSUE TITLE
Disabling GUI in configs doesn't do anything

### ISSUE THREAD

**Issue by crzyc** [XzeroAir/Trinkets-1.12.2#59] opened 2021-12-23 22:14 UTC
**Describe the bug**
The GUI disable option in the config doesn't work.

**Screenshots**
![notepad++_yQUc5hXwxz](https://user-images.githubusercontent.com/18177787/147295543-ec0b6f7f-1e2c-465d-8985-11077ca16bb6.png)

**Version (please complete the following information):**
 - Trinkets and Baubles 0.31.3

**Comment by XzeroAir** [comment] 2021-12-23 22:18
can you screenshot what you're trying to disable?
I really need to entirely redo the config I have things in there from years ago.
That setting is supposed to disable the T&B Container, it's similar to Baubles, and adds a Grey Button at the top left of your inventory, to open a container that you can put Items from T&B in.

**Comment by crzyc** [comment] 2021-12-24 02:51
Yeah, that's the thing that I'm trying to disable:
![javaw_zyesz3ioc3](https://user-images.githubusercontent.com/18177787/147309958-bc6a06e6-bec1-4c7e-a745-492341e211ad.png)

I set the config to false, but it still appears.

**Comment by XzeroAir** [comment] 2021-12-24 02:52
Have you restarted the game after disabling it?

**Comment by crzyc** [comment] 2021-12-24 02:54
Yep, multiple times. Not sure what's going wrong here.

**Comment by XzeroAir** [comment] 2021-12-24 02:58
Are any other configs not working?
I can't reproduce this, and no one I've asked has been able to reproduce this.

**Comment by crzyc** [comment] 2021-12-24 03:03
No, it's only trinkets. I'm running only rlcraft 2.8.2 but with updated baubles.

**Comment by NyanMC** [comment] 2021-12-24 03:04
this is just a guess, but @XzeroAir did you ever change the config for that gui between versions? it's possible crzyc is trying to edit an old setting that still exists due to not regenerating the config properly

**Comment by XzeroAir** [comment] 2021-12-24 03:08
I meant other T&B config options.
I did add a Lang key for that Option, but if it was broken, it should show another entry with a similar name.
But Yeah, if you're running RLCraft 2.8.2, You need to regenerate the T&B config, Delete/Rename the config file, and reload MC.
can copy over the configs you want.

RLCraft recently updated to 2.9, which includes the latest T&B version.
It also includes a lot of performance improvements, so I would recommend updating if possible.

**Comment by crzyc** [comment] 2021-12-24 03:16
I just regenerated the config file and reloaded MC, but my game still loads the GUI.

And 2.8.2 worlds aren't compatible with 2.9, unfortunately.

Edit: The other config options work fine, it's only the GUI that refuses to disappear.

**Comment by XzeroAir** [comment] 2021-12-24 04:03
If you're on a server, and the server config has that enabled, your client side config will do nothing.
if you're not playing on a server, then I'm not sure.
I'll try to look into it more.

**Comment by crzyc** [comment] 2021-12-24 04:06
I'm on single-player, so I'm at a loss there too. Thanks for your help, though.

**Comment by XzeroAir** [comment] 2021-12-24 04:15
Nevermind, I Just figured it out, Apparently I missed a check when updating some code at some point in time, I honestly have no idea how this was missed for so long, or how the people I've asked couldn't reproduce this. I'll push an update possibly sometime either tonight, or Monday.

**Comment by crzyc** [comment] 2021-12-24 04:20
Thanks so much! I thought I was going insane for a moment here. Good to know I still have some sanity left.

**Comment by crzyc** [comment] 2021-12-24 04:31
Oh, and can you tell me what version of Trinkets and Baubles doesn't have this issue, just so that I can find a way to work around it temporarily?

**Comment by XzeroAir** [comment] 2021-12-24 04:35
Most likely 0.30.1 doesn't have the issue, but, I Wouldn't recommend using that, as I've done a lot of improvements, there's a temporary solution by setting the button location to be off screen, or.... to go into the mod options, Compatibility settings, and Disabling the Elenai Dodge Compat.... Apparently I somehow managed to duplicate an entry and overwrite the gui option with that one.

**Comment by XzeroAir** [comment] 2022-01-01 18:20
had some family holiday stuff come up, so I didn't have time to work on it and upload last week.
But I have the issue fixed in my dev environment along with a few other fixes for things, have one more thing I'm trying to get implemented, and I will upload a new version in a day or two.

**Comment by XzeroAir** [comment] 2022-01-13 09:31
Sorry about that, I've been sick the past week, only started feeling better the past few days, I hate to give excuses, but was pretty bad, Regardless, I have a release candidate on my discord, going to do some tests, and if it's all good, I'll post the update tomorrow/later today (it's 4:30 AM at the time of posting this).

**Closed as completed** 2022-01-13 18:42 UTC
