### ISSUE TITLE
Fairy ring effects not being completely undone upon unequipping. 

### ISSUE THREAD

**Issue by squirrelkiller** [XzeroAir/Trinkets-1.12.2#15] opened 2019-08-24 02:51 UTC
After removing the Fairy Ring the resize effect wasn't fully undone correctly. At first it didn't return to normal size at all, then after reequipping and removing I was full size, but couldn't climb stairs. After one instance I was full size but could fly still.

**Comment by XzeroAir** [comment] 2019-08-24 18:24
Are you Using the Latest Version of Trinkets and Baubles? were you on Single Player or Multiplayer/Server.
Also, are You using the Optional ArtemisLib Dependency or no?

**Comment by XzeroAir** [comment] 2019-10-11 01:44
Closing because lack of Information, and Unable to reproduce

**Closed by XzeroAir** 2019-10-11 01:44 UTC
